### ISSUE TITLE
Can't discover ip when in different subnet

### ISSUE THREAD

**Issue by TheBlackBush** [NightRang3r/Switcher-V2-Python#1]
Hi,

Thank you for that script, very useful!
My network is divided to multiple subnets, and my my devices (PC, NAS, HA...) and switcher are not on the same subnet.
So when i try to discover my ip of the switcher it doesn't recognise it.

Any chance that you can add an option to the extract that i can provide the ip of the switcher?

**Comment by NightRang3r** [comment]
Sorry, Not possible, The auto extract and auto IP detection works as following:

The script creates a listener on port 20002 UDP and wait for broadcasts from the switcher device.

If you are not on the same subnet it means you are not on the same broadcast domain and you will not be able to receive the broadcasts from the switcher device
