### ISSUE TITLE
Which versions are supported?

### ISSUE THREAD

**Issue by BackSlasher** [NightRang3r/Switcher-V2-Python#12]
Hi.
Considering buying a Switcher, would like to do that only if supported by this repo.
1. Are both V2 and V3 (touch) supported?
2. Should I worry about firmware versions?
  I saw that some parameter extractions are hard, but that those parameters are not needed, so I'm confused whether this is a concern or not.

Awesome work 🎉

**Comment by NightRang3r** [comment]
Both versions should be supported, I just bought switcher touch and It’s working 

Supported firmwares are listed in the README file 
Not sure if there’s a new version of the firmware which is not supported
