### ISSUE TITLE
python script no longer detects Switcher Touch

### ISSUE THREAD

**Issue by gargamelonly** [NightRang3r/Switcher-V2-Python#17]
Since yesterday, without any changes to the network or host, the python script no longer detects switcher Touch device on the network.
So it is not possible to control the switcher anymore.
Do you know if there was some change from Switcher firmware side recently?
The Switcher Firmware is currently on version 5.15

**Comment by NightRang3r** [comment]
@gargamelonly I have no idea why, I am not maintaining this script anymore, I have a switcher touch with firmware 3.22, I can test if it works with my version, as for yours maybe they've changed the broadcast port or tcp port you will have to investigate

**Comment by gargamelonly** [comment]
Thanks. I will check.
Closing issue.
