### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by Harel-M** [NightRang3r/Switcher-V2-Python#2]
Hi, I've learned all the parameters (ip, phone_id, device_id and device_pass) using the extract option.
The get status option is working (switcher.py 2), I see the device name and on/off status, so the parameters are probably correct, but when I send commands the device is not doing anything.
I do not get any error from the script, and I see that I get session ID, but the device is not turning on or off.
I see a packet that is sent to the device IP from the PC IP, but it's not working.
I tried on (1), off (0) and on for X minutes (e.g. t5), all with the same result.

Any ideas?

**Comment by NightRang3r** [comment]
What is your device firmware version?

**Comment by Harel-M** [comment]
71.0

**Comment by Harel-M** [comment]
I captured the packet sent by the app and found out the last digit of the password found by the script was wrong. funny it was working for getting the status...
with the password from the capture it is working, although it looks like the syntax of the command sent by the app is a bit different (it sends the device_id before the TimeStamp for example...)

anyway, it works :)

**Comment by NightRang3r** [comment]
Glad to hear it worked out for you
