### ISSUE TITLE
extract not working

### ISSUE THREAD

**Issue by stepanov1975** [NightRang3r/Switcher-V2-Python#3]
Hi,

I have switcher v2 firmware 3.0
discover option works fine but extract option doesn't work
I am getting 
[*] Waiting for broadcast from Switcher device...
[*] Sending Login Packet to Switcher...
[+] Received SessionID: 00000000

Then the next stage fails with
[+] Press the "Enter" key to continue...
[*] Waiting for a valid Phone ID Packet...
[!] Failed to get data, Please try again!

Thank you

**Comment by danielbenzvi** [comment]
I'm seeing the same issue here

**Comment by NightRang3r** [comment]
I can’t debug the issue without an updated device, If one of you would like to give me remote access I can take a look and try to understand what was changed

**Comment by danielbenzvi** [comment]
Sure. What do you need?

**Comment by NightRang3r** [comment]
@danielbenzvi I need a team viewer session to a pc on the same network with the switcher device and the script so i can see the problem.

**Comment by stepanov1975** [comment]
Can do tomorrow let say 21:00 Israel time. But can't you update yours?:)

**Comment by NightRang3r** [comment]
@stepanov1975 No, I don't want to lose control, in case that the company  made changes that prevents external operation in this firmware.

I'm not sure about tomorrow but Ping me tomorrow at 21:00 anyway maybe I'll be available.

**Comment by stepanov1975** [comment]
ok

**Comment by dmatik** [comment]
Hi,
I'm having the same issue, however, when I first bought the device it was on earlier version of the firmware and was able to successfully extract the data. Later on I have updated the firmware and yet I still was able to turn on and off the device from HA with the same data.
Today I had to reconnect the device from scratch to the Router and since then I have no control and not able to extract the data for the same reason explained above.
So this means that they did not close it completely, as I was still able to control until I have reset it.

**Comment by NightRang3r** [comment]
@dmatik Thank you for the update, We are invesigating the issue, Hope we will be able to resolve it.

**Comment by dmatik** [comment]
You can totally use my help if you need to connect to my device or let me know if I can check some logs and test changes you do. 
Seem like the script is not getting the session id

**Comment by NightRang3r** [comment]
@dmatik Thanks man, I will need help, I have the device and development boards but I don’t have the option to upgrade to the latest firmware mine still shows version 71.0 as the latest version.

I will let you know when I need assistance

**Comment by stepanov1975** [comment]
i am ready

**Comment by stepanov1975** [comment]
So what happens?

**Comment by stepanov1975** [comment]
Still waiting ;)
Before I am throwing out my Switcher and replacing by something I will be able to control :)

**Comment by TheBlackBush** [comment]
I have the same problem, im using the Switch V3, i had that issue also on the V2

**Comment by TheBlackBush** [comment]
is there any update regarding the issue?

**Comment by galzil** [comment]
The error occurs because of the phone_id line:
`phone_id = sys.argv[1]`
What do we need to change there?

**Comment by stepanov1975** [comment]
Update from my side. I will order this https://www.aliexpress.com/item/32984039564.html and flash it with tasmota. This will solve all my problems. Anyone want my switcher for half price?:)

**Comment by TheBlackBush** [comment]
I've succeeded to retrieve the credentials of my switcher through the sqlite db.
I can see the state of the device through the script but i cant change the state and i dont get any error.
from the script everything looks fine, but it cant change anything in the switcher itself.

**Comment by dmatik** [comment]
Try to retrieve the details again
The pass is wrong, that happens. 
Try to add 1 to last digit of the pass

**Comment by TheBlackBush** [comment]
Do i need to increase by one 1 or add another digit 1?
do i do that before or after the hex converting?

**Comment by TheBlackBush** [comment]
I've succeeded!
it was my mistake i didnt saw that i need to retrieve the pass in binary mode...

so the only problem is with the Extract script

**Comment by galzil** [comment]
Did you try adding the phone_id = "0000" when running it?
`python extractV3.py 0000`

**Comment by TheBlackBush** [comment]
@galzil Yes i tried that, its not working

**Comment by chu11u** [comment]
> Update from my side. I will order this https://www.aliexpress.com/item/32984039564.html and flash it with tasmota. This will solve all my problems. Anyone want my switcher for half price?:)

Have you managed to flash the touch switch with tasmota?

**Comment by stepanov1975** [comment]
> > Update from my side. I will order this https://www.aliexpress.com/item/32984039564.html and flash it with tasmota. This will solve all my problems. Anyone want my switcher for half price?:)
> 
> Have you managed to flash the touch switch with tasmota?

Yes. Using tuya converter.

**Comment by chu11u** [comment]
Great! thanks! do you know if the device can do power metering using the Tasmota code?

**Comment by naor1** [comment]
Hi,

There is any update about this issue? still unable to extract data.

Thanks.

**Comment by macguru341** [comment]
Me too in same situation, I can’t extract the switcher info for using it with home Assistant.
I really hope it will be fixed as this is the only device I have that isn’t connect to my smart home.
How the developer find a solution.
I have the switcher touch with version 1.51

**Comment by stepanov1975** [comment]
I don't think this code supported anymore. For now, AFAIK, the best solution if you want connection to HA is Selly1PM. Rated 16A and power metering. MQTT out of the box.

**Comment by NightRang3r** [comment]
It seems extraction is not needed for newer firmware versions, All is explained in the README file

[https://github.com/NightRang3r/Switcher-V2-Python#important-update](https://github.com/NightRang3r/Switcher-V2-Python#important-update)
