### ISSUE TITLE
Switcher smart plug support

### ISSUE THREAD

**Issue by danstr1** [NightRang3r/Switcher-V2-Python#5]
Hi,

May you add support for the new [switcher smart plug](https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/%D7%A1%D7%95%D7%95%D7%99%D7%A6%D7%A8-smart-plug/)? 
I extract the db with android root device and also have packet captures that I can send you by email.
The FW version is 1.41

Thanks,
Dan

**Comment by NightRang3r** [comment]
@danstr1 Sorry, I don't have the smart plug so I don't think I will add support for it.
