### ISSUE TITLE
Switcher Touch different IP in AP mode

### ISSUE THREAD

**Issue by leranp** [NightRang3r/Switcher-V2-Python#6]
When trying to Configure Switcher in Access Point Mode the local IP of the device is 192.168.4.1 and not 192.168.1.1
after changing the IP in the script the connection worked

please add this line in the code
`elif (( ba.hexlify(data)[0:4] != "fef0" and len(data) != 165 )) or (( addr[0] != "192.168.4.1" )):
				print "[!] Not a switcher configuration broadcast message!"`

**Comment by NightRang3r** [comment]
@leranp Done!
