### ISSUE TITLE
Switcher Plug

### ISSUE THREAD

**Issue by royby12** [NightRang3r/Switcher-V2-Python#7]
Any plan to support the Switcher Plug?
I’ve tried to use the same script to extract the plug data but with no luck...

**Comment by NightRang3r** [comment]
@royby12 I don't own a Switcher plug so unless someone provides me with a test unit, I'm not planning on supporting it.

**Comment by MohammadAG** [comment]
For what it's worth, I recently got the smart plug and the script works for me the same way it does for the V2.
